'use strict';
const $=id=>document.getElementById(id);
let token='',jobs=[],current=null,report=null,frameIndex=0,selected=0,frameImage=null,playing=false,playTimer=null,renderVersion=0,lastState='',busy=false;
const main=$('mainCanvas'),ctx=main.getContext('2d');
function log(message){const p=document.createElement('p'),t=document.createElement('time');t.textContent=new Date().toLocaleTimeString();p.append(t,document.createTextNode(message));$('log').prepend(p);while($('log').children.length>100)$('log').lastChild.remove();}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,7000);log(message);}
async function api(url,obj){const res=await fetch(url,obj?{method:'POST',headers:{'Content-Type':'application/json','X-Neon-Token':token},body:JSON.stringify(obj)}:{});const data=await res.json();if(!res.ok)throw Error(data.error||'Request failed');return data;}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${(s%60).toFixed(2).padStart(5,'0')}`;}
function stop(){playing=false;clearTimeout(playTimer);$('play').textContent='▶';}
function resetViewer(){stop();renderVersion++;report=null;frameImage=null;frameIndex=0;ctx.clearRect(0,0,main.width,main.height);$('empty').hidden=false;$('seek').disabled=true;$('seek').value=0;$('play').disabled=true;$('snapshot').disabled=true;$('detections').replaceChildren();$('exports').replaceChildren();$('countTag').textContent='0 DETECTIONS';$('timestamp').textContent='00:00.00';$('metricLatency').textContent='—';$('dimensions').textContent='NO SOURCE';clearDetails();drawChart();}
function clearDetails(){for(const id of ['detailClass','detailConfidence','detailXY','detailSize','detailFrame'])$(id).textContent='—';$('crop').getContext('2d').clearRect(0,0,320,200);$('cropNote').textContent='No detection selected';}
function updateStatus(){const j=current;if(!j)return;$('filename').textContent=j.name;$('state').textContent=j.state.toUpperCase();$('message').textContent=j.error||j.message;$('progress').value=j.progress||0;$('start').disabled=j.state!=='uploaded'||busy;$('cancel').disabled=!['queued','running'].includes(j.state);$('metricFrames').textContent=j.processed||0;$('metricBoxes').textContent=j.detection_count||0;$('metricTime').textContent=j.elapsed_seconds?`${j.elapsed_seconds}s`:'—';if(j.width)$('dimensions').textContent=`${j.width} × ${j.height} | ${j.kind==='image'?'IMAGE':j.source_fps.toFixed(1)+' FPS SOURCE'}`;if(lastState!==j.id+j.state){lastState=j.id+j.state;log(`${j.name}: ${j.state}${j.error?' — '+j.error:''}`);}}
async function refresh(){try{jobs=await api('/api/jobs');if(current){current=jobs.find(j=>j.id===current.id)||null;updateStatus();if(current&&['completed','cancelled'].includes(current.state)&&!report){await loadResults(current.id);}}renderJobs();}catch(e){toast(e.message);}}
function renderJobs(){const list=$('jobs');list.replaceChildren();for(const j of jobs){const row=document.createElement('div');row.className='job'+(current?.id===j.id?' active':'');const b=document.createElement('button');b.textContent=j.name;b.title=j.name;b.onclick=()=>selectJob(j);const s=document.createElement('small');s.textContent=j.state;const del=document.createElement('button');del.className='delete';del.textContent='×';del.title='Delete source and results';del.disabled=['queued','running','uploading'].includes(j.state);del.onclick=async()=>{if(!confirm('Delete this media and its results?'))return;try{await api('/api/delete',{id:j.id});if(current?.id===j.id){current=null;resetViewer();$('filename').textContent='No media selected';$('state').textContent='READY';$('start').disabled=true;$('cancel').disabled=true;$('message').textContent='Upload media to begin.';for(const id of ['metricFrames','metricBoxes'])$(id).textContent='0';$('metricTime').textContent='—';$('progress').value=0;}await refresh();}catch(e){toast(e.message);}};row.append(b,s,del);list.append(row);}if(!jobs.length)list.textContent='No sessions yet. Upload media to begin.';}
async function selectJob(j){current=j;resetViewer();updateStatus();renderJobs();if(['completed','cancelled'].includes(j.state))await loadResults(j.id);}
async function loadResults(id){try{const data=await api(`/files/${id}/results.json`);if(current?.id!==id)return;report=data;$('empty').hidden=!!data.samples.length;$('seek').max=Math.max(0,data.samples.length-1);$('seek').disabled=!data.samples.length;$('play').disabled=data.samples.length<2;$('snapshot').disabled=!data.samples.length;$('exports').replaceChildren();for(const [name,file]of [['JSON report','results.json'],['CSV detections','detections.csv'],[current.kind==='image'?'Annotated image':'Annotated video (AVI)',current.kind==='image'?'annotated.jpg':'annotated.avi']]){const a=document.createElement('a');a.textContent='⇩  '+name;a.href=`/files/${id}/${file}`;a.download=file;$('exports').append(a);}if(data.samples.length)await showFrame(0);drawChart();}catch(e){if(current?.id===id&&current.state==='completed')toast('Could not load results: '+e.message);}}
async function showFrame(index){if(!report?.samples.length)return;const version=++renderVersion;frameIndex=Math.max(0,Math.min(index,report.samples.length-1));selected=0;const s=report.samples[frameIndex],img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Review frame unavailable'));img.src=`/files/${current.id}/${s.image}`;}).catch(e=>toast(e.message));if(version!==renderVersion||!img.naturalWidth)return;frameImage=img;main.width=report.width;main.height=report.height;$('seek').value=frameIndex;$('timestamp').textContent=formatTime(s.time);$('frameTag').textContent=`FRAME ${s.frame} · ${s.detections.length} DETECTIONS`;$('metricLatency').textContent=`${s.inference_ms.toFixed(0)} ms`;drawFrame();renderDetections();drawChart();}
function drawFrame(){if(!frameImage||!report)return;ctx.drawImage(frameImage,0,0,main.width,main.height);const s=report.samples[frameIndex];if($('boxes').checked)s.detections.forEach((d,i)=>{const[x1,y1,x2,y2]=d.box;ctx.strokeStyle=i===selected?'#00e798':'#79caff';ctx.lineWidth=Math.max(2,main.width/500);ctx.strokeRect(x1,y1,x2-x1,y2-y1);if($('labels').checked){ctx.font=`${Math.max(13,main.width/65)}px monospace`;const txt=`${d.label} ${(d.confidence*100).toFixed(0)}%`,tw=ctx.measureText(txt).width;const top=Math.max(0,y1-24);ctx.fillStyle='#00111ee8';ctx.fillRect(x1,top,tw+10,23);ctx.fillStyle='#42ffab';ctx.fillText(txt,x1+5,top+17);}});const d=s.detections[selected];if(!d){clearDetails();return;}const[x1,y1,x2,y2]=d.box;$('detailClass').textContent=d.label;$('detailConfidence').textContent=(d.confidence*100).toFixed(1)+'%';$('detailXY').textContent=`${x1}, ${y1}`;$('detailSize').textContent=`${x2-x1} × ${y2-y1}`;$('detailFrame').textContent=s.frame;const c=$('crop').getContext('2d');c.clearRect(0,0,320,200);if(x2>x1&&y2>y1){const scale=Math.min(320/(x2-x1),200/(y2-y1)),w=(x2-x1)*scale,h=(y2-y1)*scale;c.drawImage(frameImage,x1,y1,x2-x1,y2-y1,(320-w)/2,(200-h)/2,w,h);}$('cropNote').textContent=`${d.label} · resized crop, not additional sensor detail`;}
function renderDetections(){const body=$('detections');body.replaceChildren();const ds=report.samples[frameIndex].detections;$('countTag').textContent=`${ds.length} DETECTIONS`;ds.forEach((d,i)=>{const row=document.createElement('tr');row.className=i===selected?'selected':'';for(const value of [d.label,(d.confidence*100).toFixed(1)+'%',`${d.box[2]-d.box[0]} × ${d.box[3]-d.box[1]}`]){const td=document.createElement('td');td.textContent=value;row.append(td);}row.onclick=()=>{selected=i;drawFrame();renderDetections();};body.append(row);});if(!ds.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;td.textContent='No objects above the selected confidence threshold.';row.append(td);body.append(row);}}
function drawChart(){const c=$('chart'),g=c.getContext('2d'),w=c.width,h=c.height;g.clearRect(0,0,w,h);const samples=report?.samples||[],max=Math.max(1,...samples.map(s=>s.detections.length));g.font='11px monospace';for(let i=0;i<=4;i++){const y=15+i*35;g.strokeStyle='#15304b';g.beginPath();g.moveTo(30,y);g.lineTo(w-10,y);g.stroke();g.fillStyle='#759fbf';g.fillText((max*(1-i/4)).toFixed(0),2,y+4);}if(!samples.length){g.fillStyle='#537e9f';g.fillText('Analysis data appears here',170,90);return;}g.strokeStyle='#00e798';g.lineWidth=2;g.beginPath();samples.forEach((s,i)=>{const x=30+i/Math.max(1,samples.length-1)*(w-45),y=155-s.detections.length/max*140;i?g.lineTo(x,y):g.moveTo(x,y);});g.stroke();const x=30+frameIndex/Math.max(1,samples.length-1)*(w-45);g.strokeStyle='#60baff';g.beginPath();g.moveTo(x,12);g.lineTo(x,160);g.stroke();g.fillStyle='#8db4d1';g.fillText('0s',30,180);g.fillText(samples.at(-1).time.toFixed(1)+'s',w-65,180);}
async function tick(){if(!playing||!report)return;if(frameIndex>=report.samples.length-1){stop();return;}const before=performance.now(),next=frameIndex+1,delay=(report.samples[next].time-report.samples[frameIndex].time)*1000/Number($('speed').value);await showFrame(next);if(playing)playTimer=setTimeout(tick,Math.max(15,delay-(performance.now()-before)));}
$('play').onclick=async()=>{if(playing)return stop();if(frameIndex>=report.samples.length-1)await showFrame(0);playing=true;$('play').textContent='Ⅱ';tick();};
$('seek').oninput=()=>{stop();showFrame(Number($('seek').value));};
$('boxes').onchange=$('labels').onchange=drawFrame;
$('confidence').oninput=()=>{$('confValue').textContent=$('confidence').value+'%';};
$('refresh').onclick=refresh;$('clearLog').onclick=()=>$('log').replaceChildren();
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;if(f.size>250*1024*1024){toast('File exceeds 250 MB.');return;}busy=true;$('file').disabled=true;$('uploadStatus').textContent='Uploading…';try{const res=await fetch('/api/upload?name='+encodeURIComponent(f.name),{method:'POST',headers:{'X-Neon-Token':token,'Content-Type':'application/octet-stream'},body:f}),j=await res.json();if(!res.ok)throw Error(j.error);await selectJob(j);await refresh();log('Upload complete: '+f.name);}catch(e){toast(e.message);}finally{busy=false;$('file').disabled=false;$('file').value='';$('uploadStatus').textContent='';updateStatus();}};
$('start').onclick=async()=>{if(!current)return;busy=true;updateStatus();try{current=await api('/api/start',{id:current.id,confidence:Number($('confidence').value)/100,stride:Number($('stride').value),size:Number($('size').value)});resetViewer();}catch(e){toast(e.message);}finally{busy=false;updateStatus();await refresh();}};
$('cancel').onclick=async()=>{try{await api('/api/cancel',{id:current.id});log('Cancellation requested; finishing the current frame.');}catch(e){toast(e.message);}};
$('snapshot').onclick=()=>{main.toBlob(blob=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`detection-frame-${report.samples[frameIndex].frame}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};
main.onclick=e=>{if(!report)return;const r=main.getBoundingClientRect(),x=(e.clientX-r.left)*main.width/r.width,y=(e.clientY-r.top)*main.height/r.height;const ds=report.samples[frameIndex].detections;const n=ds.findIndex(d=>x>=d.box[0]&&x<=d.box[2]&&y>=d.box[1]&&y<=d.box[3]);if(n>=0){selected=n;drawFrame();renderDetections();}};
async function init(){try{const c=await api('/api/config');token=c.token;$('health').textContent=c.model_ready?'● MODEL READY':'● MODEL MISSING';if(!c.model_ready)toast('Run python scripts/download_model.py to install the detector.');log('Studio ready. Files are processed locally.');await refresh();if(jobs.length)await selectJob(jobs[0]);}catch(e){$('health').textContent='● DISCONNECTED';toast(e.message);}setInterval(()=>{$('clock').textContent=new Date().toLocaleString();},1000);setInterval(refresh,1500);drawChart();}init();
